### ISSUE TITLE
[Suggestion] category settings

### ISSUE THREAD

**Issue by ZehelFenris** [cr4ckp0t/AdiBags_EmeraldDream#1]
Would it be possible to get settings to enable/disable which items go in the Emerald Dream section? They could be sorted into the following sections.
- Equipment/Cosmetic
- Knowledge
- Mounts
- Openable
- Other
- Pets
- Quest
- Reagent
- Reputation
- Toys

Or at the very least have them sorted into sections in the code by use of comments so people are able to easily comment out the sections they don't want.

**Comment by cr4ckp0t** [comment]
Sure, I can definitely do that.

**Comment by cr4ckp0t** [comment]
Added this in 1.1.1. Thanks for the suggestion!
