### ISSUE TITLE
Items missing

### ISSUE THREAD

**Issue by Hayato2846** [cr4ckp0t/AdiBags_EmeraldDream#2]
Hey :)

Thanks for your addon!

I noticed some items are missing so I'll just list them:

https://wowhead.com/item=211370
https://wowhead.com/item=211366
https://wowhead.com/item=210954
https://wowhead.com/item=211373
https://wowhead.com/item=211303
https://wowhead.com/item=211374

Thanks!

**Comment by cr4ckp0t** [comment]
Got these added in 1.1.0. Thanks!
